### ISSUE TITLE
Hibernate issue with GF4

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#568]
There are a lot of warnings in the glassfish server.log (bes domain) with hibernate and class loading regarding the trigger checks:

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)] Parent -> org.glassfish.internal.api.DelegatingClassLoader@a5b08bc
 was requested to find class tppi.dataContainer after done was invoked from the following stack trace
java.lang.Throwable
	at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:825)
	at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:742)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:209)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)

The same stack trace is described in solved [Hibernate bug](https://hibernate.atlassian.net/browse/HHH-11245?attachmentViewMode=list), reported for Glassfih 4.1.1 and Hibernate core 5.2.4 and fixed in 5.2.5.

OSCM is using Hibernate core 5.0.9.Final

**Comment by StavrevaS** [comment]
@DawidCh, @redmond2683 is trying to update Hibernate to 5.2.5.
If you know some reason against it, please write. Maybe you have already tested higher versions?

**Comment by StavrevaS** [comment]
Started update in https://github.com/servicecatalog/development/tree/glassfish4_hibernate_upgrade

**Comment by badziakp** [comment]
I analyzed described issue and reproduced the problem locally. Exception is thrown but it doesn't affect working of queries. I run IT tests using problematic queries without any problems. I also tested manually cases in which exception occurs and they work fine.

**Comment by StavrevaS** [comment]
The issue has no functional impact. It is also stated in the [Hibernate bug](https://hibernate.atlassian.net/browse/HHH-11245?attachmentViewMode=list).
It will produce only a lot of warnings in the server.log.

**Comment by SylviaDehn** [comment]
These warnings will fill up the logfile. WARNINGS are no good. Default log level is INFO. See logfile attached in bug 564.

**Comment by SylviaDehn** [comment]
![image](https://cloud.githubusercontent.com/assets/15086024/23363264/237d5278-fcfa-11e6-8c5e-bf8e89122554.png)

**Comment by SylviaDehn** [comment]
How about changing the log level of hibernate? Or using the fixed version of hibernate?

**Comment by SylviaDehn** [comment]
Also an ERROR occurs in server.log file . I do not know if this is the same problem:

[2017-02-27T14:48:51.002+0100] [glassfish 4.1] [ERROR] [] [org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl] [tid: _ThreadID=228 _ThreadName=p: thread-pool-1; w: 27] [timeMillis: 1488203331002] [levelValue: 1000] [[
  HHH000260: Exception calling user Synchronization [org.hibernate.search.backend.impl.EventSourceTransactionContext$BeforeCommitSynchronizationDelegator@4edc024f] : java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils]]

**Comment by DawidCh** [comment]
I have moved https://github.com/servicecatalog/development/issues/568#issuecomment-282724591 to another issue as this is sth new - #586 
@SylviaDehn could you please provide info how to reproduce the issue, if you have any idea.
Hibernate version is fixed and (in my opinion) cannot be upgraded, because of dependencies. Level of logging - unfortunately not an option. The issue  will be probably open untill bug in Hibernate (https://github.com/servicecatalog/development/issues/568#issuecomment-282239106) will be fixed.
If anyone has other idea, post it here please.

**Comment by SylviaDehn** [comment]
I do not have to do anything to reproduce this. The warnings keep being logged. I use my migrated db.
Doing nothing is not an option here. This cannot be delivered as is.

**Comment by badziakp** [comment]
[Details of fix]
Logging level of javax.enterprise.system.util was set to SEVERE

**Comment by GoebelL** [comment]
@SylviaDehn Please verify if the issue is solved.

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-84-20170406062322 in SAML mode.
In logfiles from bes and master-indexer I cannot see any errors, but in log from app domain the problem does still occurs althought in glassfish console I can see variable javax.enterprise.system.util set to SEVERE

**Comment by badziakp** [comment]
I checked it on app domain and described exception is thrown only in setting domain process. It is caused because logging configuration is not yet set. When app-domain is running the exception doesn't appear.
